# Generated by Django 3.2.4 on 2022-05-07 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('destination', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Oder',
        ),
        migrations.AddField(
            model_name='channel',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='channel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.channel'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.delivery'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='app.Product'),
        ),
        migrations.AddField(
            model_name='customer',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.order'),
        ),
    ]
