# Generated by Django 3.2.4 on 2022-05-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220507_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
