# Generated by Django 3.2.4 on 2022-05-10 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.channel'),
        ),
    ]
